services:
  db:
    image: postgres:latest
    container_name: transactions_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d transactions"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
 db_data: